server:
  servlet:
    context-path: ${SERVER_PATH}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-version: 1
    schemas: public
    locations: classpath:db/migration
    sql-migration-suffixes: .sql
    baseline-on-migrate: true
    sql-migration-prefix: V